import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { motion } from 'motion/react';
import { FileCode2, Database, Shield, Radio, Cpu, MessageSquare, Server, Cloud } from 'lucide-react';

export default function Architecture() {
  const sections = [
    {
      id: 'folder-structure',
      title: '1. Project Folder Structure',
      icon: FileCode2,
      content: `
aerosphere-network/
├── app/                  # Next.js 14 App Router
│   ├── (auth)/           # Authentication routes
│   ├── (dashboard)/      # Protected dashboard routes
│   ├── api/              # API Routes (Stripe, AI, WebRTC signaling)
│   ├── globe/            # Interactive Mapbox/Three.js globe
│   ├── podcasts/         # Podcast episode pages
│   └── layout.tsx        # Root layout
├── components/           # Reusable UI components
│   ├── ui/               # Tailwind/shadcn UI components
│   ├── podcast/          # Waveform player, episode cards
│   ├── community/        # Chat, forums, Q&A boards
│   └── globe/            # 3D globe components
├── lib/                  # Utility functions and configurations
│   ├── supabase/         # Supabase client & types
│   ├── anthropic/        # OPUS 4.6 integration logic
│   ├── webrtc/           # Live streaming logic
│   └── stripe/           # Monetization logic
├── types/                # TypeScript interfaces
├── public/               # Static assets
├── middleware.ts         # Role-based route protection
├── tailwind.config.ts    # Tailwind configuration
└── package.json          # Dependencies
      `
    },
    {
      id: 'database-schema',
      title: '2. Database Schema (PostgreSQL / Supabase)',
      icon: Database,
      content: `
-- Users Table (Extends Supabase Auth)
CREATE TABLE users (
  id UUID REFERENCES auth.users PRIMARY KEY,
  role TEXT CHECK (role IN ('public', 'host', 'architect', 'moderator', 'admin')),
  username TEXT UNIQUE,
  avatar_url TEXT,
  bio TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Podcasts Table
CREATE TABLE podcasts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  host_id UUID REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT,
  audio_url TEXT,
  is_live BOOLEAN DEFAULT FALSE,
  transcript TEXT, -- Generated by OPUS 4.6
  summary TEXT,    -- Generated by OPUS 4.6
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Community Chat Table
CREATE TABLE chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  podcast_id UUID REFERENCES podcasts(id),
  user_id UUID REFERENCES users(id),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Innovation Hub (Research/Prototypes)
CREATE TABLE research_projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  architect_id UUID REFERENCES users(id),
  title TEXT NOT NULL,
  github_repo_url TEXT,
  description TEXT,
  tags TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);
      `
    },
    {
      id: 'auth-architecture',
      title: '3. Authentication Architecture',
      icon: Shield,
      content: `
- Provider: Supabase Auth (Email/Password, OAuth via GitHub/Google)
- Session Handling: JWT stored in secure HTTP-only cookies.
- Flow:
  1. User signs in via \`/login\`.
  2. Supabase issues JWT.
  3. Next.js Middleware intercepts requests to protected routes (e.g., \`/dashboard\`).
  4. Middleware verifies JWT and checks the user's \`role\` claim.
  5. If unauthorized, redirects to \`/login\` or \`/unauthorized\`.
      `
    },
    {
      id: 'live-streaming',
      title: '4. Live Streaming Architecture',
      icon: Radio,
      content: `
- Protocol: WebRTC for low-latency peer-to-peer or client-server streaming.
- Signaling Server: Socket.io running on a custom Node.js microservice or Next.js API routes (if using serverless WebSockets like Pusher/Ably).
- Flow:
  1. Host initiates stream -> Creates WebRTC Offer.
  2. Offer sent to Signaling Server.
  3. Listeners connect -> Send WebRTC Answer.
  4. ICE Candidates exchanged via Signaling Server.
  5. Direct P2P connection established (or via TURN server like Twilio if NAT traversal fails).
- Recording: Host's local stream is recorded and uploaded to Supabase Storage post-stream.
      `
    },
    {
      id: 'opus-integration',
      title: '5. Anthropic OPUS 4.6 Integration Logic',
      icon: Cpu,
      content: `
// lib/anthropic/client.ts
import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function generatePodcastSummary(transcript: string) {
  const response = await anthropic.messages.create({
    model: "claude-3-opus-20240229", // Assuming OPUS 4.6 maps to latest Opus
    max_tokens: 1000,
    temperature: 0.2,
    system: "You are an expert aerospace engineer and technical writer. Summarize the following podcast transcript, extracting key technical concepts, flight dynamics discussed, and generate a glossary of terms.",
    messages: [
      { role: "user", content: transcript }
    ]
  });
  return response.content;
}
      `
    },
    {
      id: 'chat-system',
      title: '7. Real-time Chat System Structure',
      icon: MessageSquare,
      content: `
- Tech Stack: Socket.io + Redis (Pub/Sub) + Supabase (Persistence)
- Architecture:
  - Client connects to Socket.io server.
  - Joins room based on \`podcast_id\`.
  - Messages emitted to room.
  - Socket.io server publishes to Redis channel (for horizontal scaling across multiple Node.js instances).
  - Background worker persists messages to Supabase \`chat_messages\` table in batches to reduce DB load.
      `
    },
    {
      id: 'middleware',
      title: '8. Middleware for Role-based Protection',
      icon: Shield,
      content: `
// middleware.ts
import { createMiddlewareClient } from '@supabase/auth-helpers-nextjs';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const supabase = createMiddlewareClient({ req, res });
  const { data: { session } } = await supabase.auth.getSession();

  const isHostRoute = req.nextUrl.pathname.startsWith('/host');
  const isAdminRoute = req.nextUrl.pathname.startsWith('/admin');

  if (!session && (isHostRoute || isAdminRoute)) {
    return NextResponse.redirect(new URL('/login', req.url));
  }

  if (session) {
    const { data: user } = await supabase.from('users').select('role').eq('id', session.user.id).single();
    
    if (isHostRoute && user.role !== 'host' && user.role !== 'admin') {
      return NextResponse.redirect(new URL('/unauthorized', req.url));
    }
    if (isAdminRoute && user.role !== 'admin') {
      return NextResponse.redirect(new URL('/unauthorized', req.url));
    }
  }

  return res;
}
      `
    },
    {
      id: 'deployment',
      title: '9. Deployment Guide (Vercel + Supabase)',
      icon: Cloud,
      content: `
1. Supabase Setup:
   - Create new project.
   - Run SQL scripts to create tables and RLS (Row Level Security) policies.
   - Configure Auth providers (GitHub, Email).
   - Get API keys and DB connection string.

2. Vercel Setup:
   - Connect GitHub repository to Vercel.
   - Configure Build Command: \`npm run build\`
   - Add Environment Variables (see section 10).
   - Deploy.

3. Signaling Server (Optional):
   - If using custom Socket.io, deploy Node.js app to Render or Railway, as Vercel Serverless functions don't support persistent WebSockets well.
      `
    },
    {
      id: 'env-vars',
      title: '10. Environment Variable Structure',
      icon: Server,
      content: `
# .env.local
NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key

ANTHROPIC_API_KEY=your_opus_4_6_api_key

NEXT_PUBLIC_MAPBOX_TOKEN=your_mapbox_gl_token

STRIPE_SECRET_KEY=your_stripe_secret_key
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key

NEXT_PUBLIC_SIGNALING_SERVER_URL=wss://your-signaling-server.com
      `
    }
  ];

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8 max-w-5xl mx-auto pb-12"
    >
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">System Architecture</h1>
        <p className="text-slate-400">Technical specifications and deliverables for the UAV Intel Africa platform.</p>
      </div>

      <div className="space-y-6">
        {sections.map((section) => (
          <Card key={section.id} className="bg-black/60 border-white/5 overflow-hidden">
            <CardHeader className="border-b border-white/5 bg-white/5 pb-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-blue-900/40 text-blue-400">
                  <section.icon className="w-5 h-5" />
                </div>
                <CardTitle className="text-lg text-slate-200">{section.title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <pre className="p-6 text-sm font-mono text-slate-300 overflow-x-auto bg-black/40">
                <code>{section.content.trim()}</code>
              </pre>
            </CardContent>
          </Card>
        ))}
      </div>
    </motion.div>
  );
}
